spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  datasource:
    username: testuser
    password: 1234
    url: "jdbc:mysql://localhost:3306/test?serverTimezone=UTC&characterEncoding=UTF-8"
    driver-class-name: com.mysql.cj.jdbc.Driver
